# raycast-style launcher, spaceduck palette
[main]
font=JetBrainsMono Nerd Font:size=16
prompt="⚡ "
placeholder=grep
icons-enabled=yes
lines=3
width=50
horizontal-pad=24
vertical-pad=16
inner-pad=8
line-height=28
anchor=center

[colors]
background=0f111bf2
text=ecf0c1ff
placeholder=ecf0c180
prompt=7a5cccff
input=ecf0c1ff
match=00a3ccff
selection=30365fff
selection-text=ecf0c1ff
selection-match=00a3ccff
border=7a5cccff

[border]
width=2
radius=0
