# Spaceduck color theme
# https://github.com/pineapplegiant/spaceduck

$background = rgb(0f111b)
$foreground = rgb(ecf0c1)
$cursorLine = rgb(16172d)
$visualSel = rgb(1b1c36)

$red = rgb(e33400)
$orange = rgb(e39400)
$green = rgb(5ccc96)
$yellow = rgb(f2ce00)
$purple = rgb(b3a1e6)
$purple2 = rgb(7a5ccc)
$darkPurple = rgb(30365F)
$darkPurple2 = rgb(686f9a)
$cyan = rgb(00a3cc)
$magenta = rgb(ce6f8f)
$grey = rgb(818596)
$grey2 = rgb(c1c3cc)
